version: "3"
services:
#  back:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: back
#    env_file:
#      - .env
#    environment:
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_DB: ${POSTGRES_DB}
#      REDIS_URL: ${REDIS_URL}
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres_db
#      - redis_server
#    volumes:
#      - ./back_container_logs:/app/logs
#    restart: unless-stopped

  postgres_db:
    image: 'postgres:15-alpine'
    container_name: postgresDB
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/netufospostgresql/data
    restart: unless-stopped

  redis_server:
    image: 'redis:alpine'
    container_name: redisServer
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:
